### ISSUE TITLE
make appimage from online archive

### ISSUE THREAD

**Issue by TasMania17** [universe-software/shradiko#1]
Thanks for the work you have done. I was able to make an appimage quite easily. 
I have a small issue. I made an appimage with the current Ubuntu LTS (20.04). This is listed on cdimage.ubuntu.com. I would like to make an appimage for the 22.04  LTS which I have installed but is not listed on cdimage releases archive. It will be there in April for sure.
Is there a way for Shradiko to reference another archive like this one?
http://cdimage.ubuntu.com/ubuntu-base/daily/current/?C=N;O=D

**Comment by TasMania17** [comment]
I solved this myself.
I extracted an Ubuntu appimage maker that uses 20.04 and edited the sources entry to point to 22.04. Then I repacked it.
UNPACK ./shradiko-apt --appimage-extract
REPACK ./appimagetool-x86_64.AppImage ./squashfs-root/

I edited shradiko-apt and made the sources point to here:
https://cdimage.ubuntu.com/ubuntu-base/daily/pending/jammy-base-amd64.tar.gz
Note. This Ubuntu version is not released until April.

**Comment by Hyperdraw** [comment]
The original plan was just to keep up with current LTS release of Ubuntu, but an option to point to a custom archive could be useful, and would even allow for other Debian-based distros. I might add that feature soon.

**Comment by TasMania17** [comment]
Hi Hyperdraw, Shradiko works great with a large app like Gimp. The Gimp appimage I made works on the current LTS also. Thanks for making this excellent software.
You could just put the squashfs-root folder on the github archive with an explanation of editing shradiko-apt if you wanted to. 

Turning deb packs into appimages solves a lot of appimage issues because they have to conform to an established install and usage regime.
